#!/usr/bin/env python3
"""tmuse: learn tmux by playing it. Run ./tmuse to start."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from game.cli import main  # noqa: E402

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except KeyboardInterrupt:
        print()
